<a href="https://colab.research.google.com/github/thokalamanasareddy-gif/AI-ML-Internship-Task1/blob/main/AI_ML_Internship_Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [9]:
import pandas as pd

df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   price            0 non-null      float64
 1   area             0 non-null      float64
 2   bedrooms         0 non-null      float64
 3   bathrooms        0 non-null      float64
 4   stories          0 non-null      float64
 5   mainroad         0 non-null      float64
 6   guestroom        0 non-null      float64
 7   basement         0 non-null      float64
 8   hotwaterheating  0 non-null      float64
 9   airconditioning  0 non-null      float64
dtypes: float64(10)
memory usage: 9.8 KB

price              124
area               124
bedrooms           124
bathrooms          124
stories            124
mainroad           124
guestroom          124
basement           124
hotwaterheating    124
airconditioning    124
dtype: int64

In [13]:
X = df[['area']]
y = df['price']

In [15]:
X = df[['area','bedrooms','bathrooms']]
y = df['price']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
model = LinearRegression()

model.fit(X_train, y_train

SyntaxError: incomplete input (1477977666.py, line 3)

In [20]:
X = X.dropna()
y = y[X.index]

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.